[book]
authors = ["Herbert Wolverson"]
language = "en"
multilingual = false
src = "src"
title = "Anduril Workshop"
edition=2021

[output.html.playground]
editable = true

[rust]
edition = "2021"

[output.html]
default-theme = "light"